create table
    "public"."z_favorite_animal" (
        "id" bigint generated by default as identity not null,
        "created_at" timestamp
        with
            time zone not null default now (),
            "name" text not null,
            "user" bigint not null
    );

create table
    "public"."z_user" (
        "id" bigint generated by default as identity not null,
        "uid" uuid not null default auth.uid (),
        "created_at" timestamp
        with
            time zone not null default now (),
            "name" text not null
    );

alter table "public"."z_user" enable row level security;

alter table "public"."z_favorite_animal" enable row level security;

-- z_userテーブルに対して、認証ユーザのみがアクセスできるようにする
create policy "本人のみ" on z_user to public using ((uid = auth.uid ()));

-- z_favorite_animalテーブルに対して、認証ユーザのみがアクセスできるようにする
create policy "本人のみ" on "public"."z_favorite_animal" to public using (
    EXISTS (
        SELECT
            1
        FROM
            "public"."z_user"
        WHERE
            (
                ("public"."z_user".uid = auth.uid ())
                AND (
                    "public"."z_favorite_animal"."user" = "public"."z_user".id
                )
            )
    )
);

CREATE UNIQUE INDEX user_sample_pkey ON public.z_user USING btree (id);

CREATE UNIQUE INDEX z_favorite_animal_pkey ON public.z_favorite_animal USING btree (id);

alter table "public"."z_favorite_animal" add constraint "z_favorite_animal_pkey" PRIMARY KEY using index "z_favorite_animal_pkey";

alter table "public"."z_user" add constraint "user_sample_pkey" PRIMARY KEY using index "user_sample_pkey";

alter table "public"."z_favorite_animal" add constraint "z_favorite_animal_user_fkey" FOREIGN KEY ("user") REFERENCES z_user (id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."z_favorite_animal" validate constraint "z_favorite_animal_user_fkey";

grant delete on table "public"."z_favorite_animal" to "anon";

grant insert on table "public"."z_favorite_animal" to "anon";

grant references on table "public"."z_favorite_animal" to "anon";

grant
select
    on table "public"."z_favorite_animal" to "anon";

grant trigger on table "public"."z_favorite_animal" to "anon";

grant truncate on table "public"."z_favorite_animal" to "anon";

grant
update on table "public"."z_favorite_animal" to "anon";

grant delete on table "public"."z_favorite_animal" to "authenticated";

grant insert on table "public"."z_favorite_animal" to "authenticated";

grant references on table "public"."z_favorite_animal" to "authenticated";

grant
select
    on table "public"."z_favorite_animal" to "authenticated";

grant trigger on table "public"."z_favorite_animal" to "authenticated";

grant truncate on table "public"."z_favorite_animal" to "authenticated";

grant
update on table "public"."z_favorite_animal" to "authenticated";

grant delete on table "public"."z_favorite_animal" to "service_role";

grant insert on table "public"."z_favorite_animal" to "service_role";

grant references on table "public"."z_favorite_animal" to "service_role";

grant
select
    on table "public"."z_favorite_animal" to "service_role";

grant trigger on table "public"."z_favorite_animal" to "service_role";

grant truncate on table "public"."z_favorite_animal" to "service_role";

grant
update on table "public"."z_favorite_animal" to "service_role";

grant delete on table "public"."z_user" to "anon";

grant insert on table "public"."z_user" to "anon";

grant references on table "public"."z_user" to "anon";

grant
select
    on table "public"."z_user" to "anon";

grant trigger on table "public"."z_user" to "anon";

grant truncate on table "public"."z_user" to "anon";

grant
update on table "public"."z_user" to "anon";

grant delete on table "public"."z_user" to "authenticated";

grant insert on table "public"."z_user" to "authenticated";

grant references on table "public"."z_user" to "authenticated";

grant
select
    on table "public"."z_user" to "authenticated";

grant trigger on table "public"."z_user" to "authenticated";

grant truncate on table "public"."z_user" to "authenticated";

grant
update on table "public"."z_user" to "authenticated";

grant delete on table "public"."z_user" to "service_role";

grant insert on table "public"."z_user" to "service_role";

grant references on table "public"."z_user" to "service_role";

grant
select
    on table "public"."z_user" to "service_role";

grant trigger on table "public"."z_user" to "service_role";

grant truncate on table "public"."z_user" to "service_role";

grant
update on table "public"."z_user" to "service_role";
