create table "public"."crazy_score" (
    "id" bigint generated by default as identity not null,
    "checked_user_uid" uuid not null,
    "post_id" bigint not null,
    "score" smallint not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."crazy_score" enable row level security;

create table "public"."language" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


alter table "public"."language" enable row level security;

create table "public"."post" (
    "id" bigint generated by default as identity not null,
    "user_uid" uuid not null,
    "title" text not null,
    "description" text not null,
    "code" text not null,
    "lang_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone
);


alter table "public"."post" enable row level security;

create table "public"."post_tag" (
    "id" bigint generated by default as identity not null,
    "post_id" bigint not null,
    "tag_id" bigint not null
);


alter table "public"."post_tag" enable row level security;

create table "public"."tag" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


alter table "public"."tag" enable row level security;

create table "public"."user" (
    "id" bigint generated by default as identity not null,
    "uid" uuid not null default gen_random_uuid(),
    "name" text not null,
    "created_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone
);


alter table "public"."user" enable row level security;

CREATE UNIQUE INDEX crazy_score_pkey ON public.crazy_score USING btree (id);

CREATE UNIQUE INDEX language_pkey ON public.language USING btree (id);

CREATE UNIQUE INDEX post_pkey ON public.post USING btree (id);

CREATE UNIQUE INDEX post_tag_pkey ON public.post_tag USING btree (id);

CREATE UNIQUE INDEX tag_pkey ON public.tag USING btree (id);

CREATE UNIQUE INDEX user_pkey ON public."user" USING btree (id);

CREATE UNIQUE INDEX user_uid_key ON public."user" USING btree (uid);

alter table "public"."crazy_score" add constraint "crazy_score_pkey" PRIMARY KEY using index "crazy_score_pkey";

alter table "public"."language" add constraint "language_pkey" PRIMARY KEY using index "language_pkey";

alter table "public"."post" add constraint "post_pkey" PRIMARY KEY using index "post_pkey";

alter table "public"."post_tag" add constraint "post_tag_pkey" PRIMARY KEY using index "post_tag_pkey";

alter table "public"."tag" add constraint "tag_pkey" PRIMARY KEY using index "tag_pkey";

alter table "public"."user" add constraint "user_pkey" PRIMARY KEY using index "user_pkey";

alter table "public"."crazy_score" add constraint "crazy_score_checked_user_uid_fkey" FOREIGN KEY (checked_user_uid) REFERENCES "user"(uid) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."crazy_score" validate constraint "crazy_score_checked_user_uid_fkey";

alter table "public"."crazy_score" add constraint "crazy_score_post_id_fkey" FOREIGN KEY (post_id) REFERENCES post(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."crazy_score" validate constraint "crazy_score_post_id_fkey";

alter table "public"."post" add constraint "post_lang_id_fkey" FOREIGN KEY (lang_id) REFERENCES language(id) not valid;

alter table "public"."post" validate constraint "post_lang_id_fkey";

alter table "public"."post" add constraint "post_user_uid_fkey" FOREIGN KEY (user_uid) REFERENCES "user"(uid) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."post" validate constraint "post_user_uid_fkey";

alter table "public"."post_tag" add constraint "post_tag_post_id_fkey" FOREIGN KEY (post_id) REFERENCES post(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."post_tag" validate constraint "post_tag_post_id_fkey";

alter table "public"."post_tag" add constraint "post_tag_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES tag(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."post_tag" validate constraint "post_tag_tag_id_fkey";

alter table "public"."user" add constraint "user_uid_key" UNIQUE using index "user_uid_key";

grant delete on table "public"."crazy_score" to "anon";

grant insert on table "public"."crazy_score" to "anon";

grant references on table "public"."crazy_score" to "anon";

grant select on table "public"."crazy_score" to "anon";

grant trigger on table "public"."crazy_score" to "anon";

grant truncate on table "public"."crazy_score" to "anon";

grant update on table "public"."crazy_score" to "anon";

grant delete on table "public"."crazy_score" to "authenticated";

grant insert on table "public"."crazy_score" to "authenticated";

grant references on table "public"."crazy_score" to "authenticated";

grant select on table "public"."crazy_score" to "authenticated";

grant trigger on table "public"."crazy_score" to "authenticated";

grant truncate on table "public"."crazy_score" to "authenticated";

grant update on table "public"."crazy_score" to "authenticated";

grant delete on table "public"."crazy_score" to "service_role";

grant insert on table "public"."crazy_score" to "service_role";

grant references on table "public"."crazy_score" to "service_role";

grant select on table "public"."crazy_score" to "service_role";

grant trigger on table "public"."crazy_score" to "service_role";

grant truncate on table "public"."crazy_score" to "service_role";

grant update on table "public"."crazy_score" to "service_role";

grant delete on table "public"."language" to "anon";

grant insert on table "public"."language" to "anon";

grant references on table "public"."language" to "anon";

grant select on table "public"."language" to "anon";

grant trigger on table "public"."language" to "anon";

grant truncate on table "public"."language" to "anon";

grant update on table "public"."language" to "anon";

grant delete on table "public"."language" to "authenticated";

grant insert on table "public"."language" to "authenticated";

grant references on table "public"."language" to "authenticated";

grant select on table "public"."language" to "authenticated";

grant trigger on table "public"."language" to "authenticated";

grant truncate on table "public"."language" to "authenticated";

grant update on table "public"."language" to "authenticated";

grant delete on table "public"."language" to "service_role";

grant insert on table "public"."language" to "service_role";

grant references on table "public"."language" to "service_role";

grant select on table "public"."language" to "service_role";

grant trigger on table "public"."language" to "service_role";

grant truncate on table "public"."language" to "service_role";

grant update on table "public"."language" to "service_role";

grant delete on table "public"."post" to "anon";

grant insert on table "public"."post" to "anon";

grant references on table "public"."post" to "anon";

grant select on table "public"."post" to "anon";

grant trigger on table "public"."post" to "anon";

grant truncate on table "public"."post" to "anon";

grant update on table "public"."post" to "anon";

grant delete on table "public"."post" to "authenticated";

grant insert on table "public"."post" to "authenticated";

grant references on table "public"."post" to "authenticated";

grant select on table "public"."post" to "authenticated";

grant trigger on table "public"."post" to "authenticated";

grant truncate on table "public"."post" to "authenticated";

grant update on table "public"."post" to "authenticated";

grant delete on table "public"."post" to "service_role";

grant insert on table "public"."post" to "service_role";

grant references on table "public"."post" to "service_role";

grant select on table "public"."post" to "service_role";

grant trigger on table "public"."post" to "service_role";

grant truncate on table "public"."post" to "service_role";

grant update on table "public"."post" to "service_role";

grant delete on table "public"."post_tag" to "anon";

grant insert on table "public"."post_tag" to "anon";

grant references on table "public"."post_tag" to "anon";

grant select on table "public"."post_tag" to "anon";

grant trigger on table "public"."post_tag" to "anon";

grant truncate on table "public"."post_tag" to "anon";

grant update on table "public"."post_tag" to "anon";

grant delete on table "public"."post_tag" to "authenticated";

grant insert on table "public"."post_tag" to "authenticated";

grant references on table "public"."post_tag" to "authenticated";

grant select on table "public"."post_tag" to "authenticated";

grant trigger on table "public"."post_tag" to "authenticated";

grant truncate on table "public"."post_tag" to "authenticated";

grant update on table "public"."post_tag" to "authenticated";

grant delete on table "public"."post_tag" to "service_role";

grant insert on table "public"."post_tag" to "service_role";

grant references on table "public"."post_tag" to "service_role";

grant select on table "public"."post_tag" to "service_role";

grant trigger on table "public"."post_tag" to "service_role";

grant truncate on table "public"."post_tag" to "service_role";

grant update on table "public"."post_tag" to "service_role";

grant delete on table "public"."tag" to "anon";

grant insert on table "public"."tag" to "anon";

grant references on table "public"."tag" to "anon";

grant select on table "public"."tag" to "anon";

grant trigger on table "public"."tag" to "anon";

grant truncate on table "public"."tag" to "anon";

grant update on table "public"."tag" to "anon";

grant delete on table "public"."tag" to "authenticated";

grant insert on table "public"."tag" to "authenticated";

grant references on table "public"."tag" to "authenticated";

grant select on table "public"."tag" to "authenticated";

grant trigger on table "public"."tag" to "authenticated";

grant truncate on table "public"."tag" to "authenticated";

grant update on table "public"."tag" to "authenticated";

grant delete on table "public"."tag" to "service_role";

grant insert on table "public"."tag" to "service_role";

grant references on table "public"."tag" to "service_role";

grant select on table "public"."tag" to "service_role";

grant trigger on table "public"."tag" to "service_role";

grant truncate on table "public"."tag" to "service_role";

grant update on table "public"."tag" to "service_role";

grant delete on table "public"."user" to "anon";

grant insert on table "public"."user" to "anon";

grant references on table "public"."user" to "anon";

grant select on table "public"."user" to "anon";

grant trigger on table "public"."user" to "anon";

grant truncate on table "public"."user" to "anon";

grant update on table "public"."user" to "anon";

grant delete on table "public"."user" to "authenticated";

grant insert on table "public"."user" to "authenticated";

grant references on table "public"."user" to "authenticated";

grant select on table "public"."user" to "authenticated";

grant trigger on table "public"."user" to "authenticated";

grant truncate on table "public"."user" to "authenticated";

grant update on table "public"."user" to "authenticated";

grant delete on table "public"."user" to "service_role";

grant insert on table "public"."user" to "service_role";

grant references on table "public"."user" to "service_role";

grant select on table "public"."user" to "service_role";

grant trigger on table "public"."user" to "service_role";

grant truncate on table "public"."user" to "service_role";

grant update on table "public"."user" to "service_role";